
GET http://localhost:5000/
###

# PRINT USERS DATABASE
GET http://localhost:5000/api/users/

###

# Get specefic user informations
GET http://localhost:5000/api/users?username=anesboz


###
# REGISTER A NEW USER
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "email": "kamal@gmail.com",
    "username": "kamal",
    "firstName": "Kamal",
    "lastName": "BOUAKAZ",
    "password": "1234567"
}

###

# LOGIN 
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "username": "kamal",
    "password": "1234567"
}

###
#Log out
DELETE http://localhost:5000/api/users/logout
###
#find profile 
GET http://localhost:5000/api/profils/users/tftf
###
#delete profile 
DELETE http://localhost:5000/api/profils/
###
#Add friend
POST http://localhost:5000/api/friends/add_friend
x-auth-token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjA1MTIzM2Y2ODU4MTRkYWExNTZiMjEyIn0sImlhdCI6MTYxNTkzNzI3NiwiZXhwIjoxNjE2Mjk3Mjc2fQ.YtPn5Un30WtixmSWkzCQeYf5y17Uof499etXX6EHtwU"
Content-Type: application/json

{
    "username": "chems01"
}
###
#Search user
POST http://localhost:5000/api/search/users
Content-Type: application/json

{
    "username": "a"
}

###
#get profiles 
GET http://localhost:5000/api/profils/

#delete users
DELETE http://localhost:5000/api/profils/