# WELCOME PAGE (inscription + connexion)
GET http://localhost:5000/
###

# DASHBOARD
GET http://localhost:5000/dashboard

###
# LIST OF USERS FROM DATABASE (ONLY FOT TESTING)
GET http://localhost:5000/api/users

###
# LOGIN 
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "chemsou@gmail.com",
    "password": "azertyui"
}

###
# PAGE OF REGISTRATION
GET http://localhost:5000/api/users/register

###
# REGISTER A NEW USER
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "email": "adscv@gmail.com",
    "firstName": "a",
    "lastName": "n",
    "password": "azertyui",
    "username": "ab"
}